### PR TITLE
zoom level and extent limits (#310 rebased) plus image-only exhibits

### LINKED ISSUE #295: Request: Set Boundary for Zooming and Panning
I've gotten a request from a student working on an Omeka to be able to "lock" a visitor in place on a Neatline Map. Ideally, the Neatline exhibit creator would be able to choose the boundary to which a visitor can zoom and pan away from the original viewport (with "not at all" being an option).

### LINKED ISSUE #430: Image-layer-only exhibits
Currently, users must select a spatial layer from a dropdown menu to serve as the base layer for a new exhibit. This means that an image layer can't be the first layer to load when the exhibit is viewed. Per #428, some users want to have exhibits where the image layer is the default view for the map — this may have been unintentionally possible prior to the last release due to an issue preventing the successful creation of Google Maps layers. Users should be able to choose to have no spatial layer as the base, or an option specifically to use the exhibit's image layer as its base in place of a spatial layer.

Related forum post: https://forum.omeka.org/t/neatline-image-layer-default-view/4333

### PR DESCRIPTION
**Pull request by akstuhl**
### What does this PR do?
This PR rebases #310 by @krdyke, "Allow user to set min/max zoom levels and restrict extent for base layer." It adds minor adjustments to cover edge case problems when loading certain layer types and and to account for zoom levels relative to the minimum level, as well as schema migrations.

It also adds the option to select no spatial layer for an exhibit, allowing users to have an image or WMS layer be the first to display.

Note: this bumps the Neatline version to 2.6.0, the anticipated next release version, in the interest of convenience for test installations.

### What issues does this address?
Closes #310, closes #295, closes #430 

### How to test
- On [staging](https://neatline-staging.herokuapp.com), go to Admin->Neatline and open a new or existing exhibit to the editor interface
- Click the Styles tab in the editor sidebar. Try adding values both manually and with the "Use Current" buttons to all fields in various combinations, saving and reloading at various points. Test zooming and panning on the map to confirm constraints and defaults have both taken effect correctly after a save+reload.
- Return to the Admin->Neatline page and click Exhibit Settings to switch the base layer type (test at least one Google layer, one Stamen layer and OpenStreetMaps), confirming that zoom/pan style settings work consistently across the different layer types.
- Also in Exhibit Settings, add a WMS layer (try @krdyke's test case of "http://nsidc.org/cgi-bin/atlas_north" for WMS Address and "land" for WMS Layers); test that this behaves correctly with the map in various constraint configurations.
### How to test, part 2:
- On [staging](https://neatline-staging.herokuapp.com), create a new exhibit. In the "Default Spatial Layer" dropdown, select "None (Image or WMS as Default)". Add an image url to the "Image Layer" field, e.g. https://upload.wikimedia.org/wikipedia/commons/e/e6/Roman_provinces_in_a_1867_school_atlas.jpg
- After saving the exhibit, load its public and editor views to check that the image displays correctly. The image should be centered in the viewer.
- Try setting default focus, default zoom, min/max zoom, and max extent values on the exhibit's style editor as described for spatial layers above. Reload to confirm that various combinations of these settings work as expected.

### CODE REVIEW

**Comment by SteveMarvin** [comment]
Adding focus and zoom values all works.
Timeline is resetting layers with any zoom or move, so can't test layer type functionality.
WMS layer attaches and works properly.

**Comment by SteveMarvin** [comment]
Layer type functionality is good.

Still have issue with timeline mucking things up.

**Comment by SteveMarvin** [comment]
Part 2 checks out. 👍

**Review by jamiefolsom — APPROVED** [review]
Looks good to me! 👍 

(Let's omit build artifacts from PRs, where possible.)

**Comment by jamiefolsom** [comment]
Also, @akstuhl -- would you close the old PR you based this on, and make a comment to the author of that? Thanks!

**Pull request merged**
