### PR TITLE
Tighten WKT formatting check in backend

### LINKED ISSUE #388: WKT strings in DC:Coverage is imported but not saved
If you link a Neatline record to an Omeka item with a WKT string in DC:Coverage, Neatline successfully fills out its own Coverage field with that string, and the geometries appear on the map. But Neatline's Coverage field is wiped after you close the item in the Editor.

On Omeka 2.4 and Neatline 2.5.1.

### LINKED ISSUE #392: Imported geometry data disappears after record is closed
Whenever I import an omeka item as a resource the corresponding geometry data is correctly imported and displayed on the map after saving - but disappears once I close the resource.

This does not happen if I modify the data. In this case both the omeka and the manual addition will show up.

### LINKED ISSUE #398: Google Maps API Error: MissingKeyMapError
I'm getting this error ([described here](https://developers.google.com/maps/documentation/javascript/error-messages#missing-key-map-error)), even when I don't use a Google map as the base layer. 

I don't see anywhere within the Neatline Exhibit Settings to enter a Google Maps API key.

### PR DESCRIPTION
**Pull request by akstuhl**
### What does this PR do?
- Processes a coverage strings through geoPHP in order to catch formatting errors before they cause save failure
- Prevents Neatline records with coverage imported from an Omeka item from creating a map marker that won't persist

### What issues does it address?
Closes #388, closes #392

### How to test
- On [staging](http://neatline-staging.herokuapp.com/), open the editor for a new or existing Neatline exhibit.
- Add a new record and click the Item tab to select an Omeka item from the list.
 Choose an item that has been given a malformed WKT string as its coverage field,
 e.g. the "WKT Test" item current has the coverage field `(GEOMETRYCOLLECTION(POINT(-60626.80528947, 6661916.076664))`, which contains an extraneous comma
- Click save after selecting the item; the record should save successfully, but no map marker should appear. Clicking on the Map tab should show no value in the Coverage field.
- Repeat the process with an item that has correctly formatted WKT in the coverage field (e.g. remove the comma from the WKT Test item's coverage value). The map marker should appear upon save. Closing the record should cause the map marker to momentarily disappear but then reappear as map layer are refreshed.

### CODE REVIEW

**Comment by jamiefolsom** [comment]
In the cover letter, I think you meant to say this closes #388, not #398, am I right about that?

**Review by jamiefolsom — APPROVED** [review]
Looks good to me. The only thing we might consider is how to let people know why an imported item is not saving the WKT string in the coverage field. I think it's sufficient to document it, since you're working on that anyhow. 👍

**Comment by akstuhl** [comment]
Thanks @jamiefolsom — corrected the issue number above and will add a documentation item.

**Comment by jeremyboggs** [comment]
👍

**Pull request merged**
