### PR TITLE
Fixed Google Maps API / OpenLayers 2 incompatibility

### LINKED ISSUE #363: Google Map Tiles Don't Load
Have an issue with Google Map tiles not displaying on the initial load of an exhibit when a Google Map (of any type) is chosen as default base layer.  

If I use the map controls to zoom in or out they appear, however.

Initial load:
initialload

After Toggling Zoom:
afterzoom

Issue does not occur when non-Google base layers are selected as the default.  

Clean install of latest Omeka and Neatline.  Same issue as http://omeka.org/forums/topic/neatline-newbie-google-maps-dont-display

### LINKED ISSUE #379: Unable to save Neatline item without geometry...
Using Neatline 2.5.1 with Omeka 2.3.1 on Mysql 5.7.10 and am unable to save a Neatline item unless I have added geometry. My logs show this error:

```
2016-01-07T14:58:30+00:00 ERR (3): exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli statement execute error : Invalid GIS data provided to function st_geometryfromtext.' in /var/www/html/omeka/application/libraries/Zend/Db/Statement/Mysqli.php:214
Stack trace:
#0 /var/www/html/omeka/application/libraries/Zend/Db/Statement.php(303): Zend_Db_Statement_Mysqli->_execute(Array)
#1 /var/www/html/omeka/application/libraries/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 /var/www/html/omeka/plugins/Neatline/models/abstract/Neatline_Row_Abstract.php(170): Zend_Db_Adapter_Abstract->query('INSERT INTO `om...', Array)
#3 /var/www/html/omeka/plugins/Neatline/models/abstract/Neatline_Row_Abstract.php(111): Neatline_Row_Abstract->insertOrUpdate(Array)
#4 /var/www/html/omeka/plugins/Neatline/models/abstract/Neatline_Row_Expandable.php(75): Neatline_Row_Abstract->save(false)
#5 /var/www/html/omeka/plugins/Neatline/models/NeatlineRecord.php(319): Neatline_Row_Expandable->save()
#6 /var/www/html/omeka/plugins/Neatline/models/NeatlineRecord.php(139): NeatlineRecord->save()
#7 /var/www/html/omeka/plugins/Neatline/controllers/RecordsController.php(58): NeatlineRecord->saveForm(Array)
#8 /var/www/html/omeka/application/libraries/Zend/Controller/Action.php(516): Neatline_RecordsController->postAction()
#9 /var/www/html/omeka/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('postAction')
#10 /var/www/html/omeka/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#11 /var/www/html/omeka/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#12 /var/www/html/omeka/application/libraries/Zend/Application.php(382): Zend_Application_Bootstrap_Bootstrap->run()
#13 /var/www/html/omeka/application/libraries/Omeka/Application.php(79): Zend_Application->run()
#14 /var/www/html/omeka/index.php(23): Omeka_Application->run()
#15 {main}
```

The workaround appears to be to draw, e.g. a point on the map, at which point it will save okay. This is however, more of a problem for my users who want to import Neatline items via CSV.

On investigation it appears that Mysql 5.6.27 the expression `GeomFromText('')` returns NULL, whereas on 5.7.10 it throws `ERROR 3037 (22023): Invalid GIS data provided to function st_geometryfromtext` instead.

I have temporarily hacked my instance of the plugin to fix this my changing `nl_setGeometry` in `helpers/Mysql.php` like so:

```
function nl_setGeometry($coverage)
{
    $coverage_or_default = $coverage ?: "POINT(0 0)";
    return new Zend_Db_Expr("COALESCE(
        GeomFromText('{$coverage_or_default}'), GeomFromText('POINT(0 0)')
    )");
 }
```

This will still fail with invalid geometry (and the user won't know why) so I'm sure there's a better solution.

### PR DESCRIPTION
**Pull request by jamiefolsom**
### What does this PR do?

- Fixes a few dev setup issues, by updating some dependencies
- Addresses #379, per the patch mentioned in that issue
- Addresses #382, #386, #398, via a custom build of OpenLayers 2, per openlayers/ol2#1489
- Related to #168, #363, #391

### How to test

**If the instance you're testing isn't yet configured**
1. Get a Google Maps API Key, per instructions [here](https://developers.google.com/maps/documentation/javascript/get-api-key)
1. Visit `/admin/plugins` and click "Configure" next to Neatline
1. Enter the key and save

**Then, or if using [staging server](http://neatline-staging.herokuapp.com/neatline/show/london)**
1. Log in as an admin (ask for credentials)
1. Visit `/admin/` and click "Neatline"
1. Click "Exhibit Settings" on a listed exhibit
1. Under "Enabled Spatial Layers", and "Default Spatial Layers", select any Google Maps base layer
1. Click "Save Exhibit" at bottom of the page
1. Click "Public view"
1. The Google Map base layer should appear under the WMS map layer. Toggle the map layers at top right, by clicking the layers menu to select which to view

The WMS map and layer in this instance is specified in a Neatline *record*; this is not yet reliable for any base layer in any view when the WMS map and/or layer is entered on the exhibit itself.

### CODE REVIEW

**Comment by SteveMarvin** [comment]
Login page: http://neatline-staging.herokuapp.com/users/login
Admin page:

**Comment by SteveMarvin** [comment]
Looking good! Ship it! 👍

**Comment by jamiefolsom** [comment]
Thanks, @SteveMarvin!

**Comment by jeremyboggs** [comment]
All looks good to me too. Per our phone conversation, @jamiefolsom, it looks like you did wrap the strings in the configuration form with Omeka's i18n functions. We should remember to update our languages base files, and post that update to Transifex. Will merge momentarily!

**Comment by jamiefolsom** [comment]
Thanks, @jeremyboggs!

**Pull request merged**
